### PR TITLE
Fix #331 overrideUrl doesn't work

### LINKED ISSUE #331: overrideUrl doesn't work
There is a bug in the code which processes the overrideUrl in org.codehaus.mojo.license.LicenseMojoUtils.prepareUrl(String, File, String, File, String):

        final Path basedirPath = basedir.toPath();

        if ( url != null && UrlRequester.isStringUrl( url ) )
        {
            return basedirPath.toUri().toString();
        }

        final Path defaultPath = basedirPath.resolve( defaultFilePath );

should be

        if ( url != null && UrlRequester.isStringUrl( url ) )
        {
            return url;
        }

        final Path basedirPath = basedir.toPath();
        final Path defaultPath = basedirPath.resolve( defaultFilePath );

### PR DESCRIPTION
**Pull request by digulla**
In addition to just checking the result, I've also added logging so users of the plugin can find out what it's loading and from where and why without having to start a debugger.

Code coverage is at 83.9%

Sore point is the DEFAULT_OVERRIDE_THIRD_PARTY which is used in the default path of the code; I could wrap the constant in a getter to switch between "exists" and "missing" cases.

### CODE REVIEW

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+    @Test
+    public void testIsValidNull()
+    {
+        assertFalse( LicenseMojoUtils.isValid( null ) );
+    }
+
+    @Test
+    public void testIsValidEmpty()
+    {
+        // TODO is this correct?
```
Comment (ppalaga) [inline src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: Yes, let's assume it is correct unless proven otherwise. Please remove the TODO.

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+        assertTrue( LicenseMojoUtils.isValid( "" ) );
+    }
+
+    @Test
+    public void testIsValidBlank()
+    {
+        // TODO is this correct?
```
Comment (ppalaga) [inline src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: Yes, let's assume it is correct unless proven otherwise. Please remove the TODO.

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+    @Test
+    public void testIsValidHttpResource()
+    {
+        assertTrue( LicenseMojoUtils.isValid( "http://foo/bar/baz" ) );
+    }
+
+    @Test
+    public void testPrepareThirdPartyOverrideUrlNull()
+    {
+        LicenseMojoUtils.prepareThirdPartyOverrideUrl( resolvedUrl, deprecatedFile, url, basedir, log );
```
Comment (ppalaga) [inline src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: Should there be no assertion about the value returned by `prepareThirdPartyOverrideUrl()`?

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+    
+    @Test
+    public void testPrepareThirdPartyOverrideUrlBothOverrides()
+    {
+        deprecatedFile = new File( "src/test/resources/overrides.properties" );
+        url = "classpath:overrides.properties";
+        try
+        {
+            LicenseMojoUtils.prepareThirdPartyOverrideUrl( resolvedUrl, deprecatedFile, url, basedir, log );
+        }
```
Comment (ppalaga) [inline src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: If the IllegalArgumentException is expected, the test should fail in case the exception is not thrown. So you probably want to add something like `Assert.fail(IllegalArgumentException.class.getSimpleName() + " expected")` on line 69

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java (hunk 1 above)
Comment (digulla) [reply src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: I've added a comment: `This might be wrong; feel free to change the test when it starts to fail` so the next person will not hesitate to fix the test.

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java (hunk 2 above)
Comment (digulla) [reply src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: See above

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java (hunk 3 above)
Comment (digulla) [reply src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: Fixed

File: src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java (hunk 4 above)
Comment (digulla) [reply src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java]: Done.

**Comment by digulla** [comment]
Just to make sure: When you ask me to "squash the commit", I do that locally and then force-push, right?

**Comment by ppalaga** [comment]
> Just to make sure: When you ask me to "squash the commit", I do that locally and then force-push, right?

Yes.

**Comment by digulla** [comment]
I'm wondering why this issue is still in the state "Changes requested". Did I miss something?

**Comment by ppalaga** [comment]
Thanks @digulla !
