### PR TITLE
Fix #354 Make artifact cache safe for concurrent access

### LINKED ISSUE #354: `ConcurrentModificationException` running `add-third-party` goal
Today I observed the following build failure, after many successful executions of the `add-third-party` goal in various large (concurrent) Maven builds:
```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (check-third-party-licenses) on project some-internal-project: could not init goal AddThirdPartyMojo for reason : null: ConcurrentModificationException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (check-third-party-licenses) on project some-internal-project: could not init goal AddThirdPartyMojo for reason : null
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
Caused by: org.apache.maven.plugin.MojoExecutionException: could not init goal AddThirdPartyMojo for reason : null
    at org.codehaus.mojo.license.AbstractLicenseMojo.execute (AbstractLicenseMojo.java:185)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.util.ConcurrentModificationException
    at java.util.TreeMap$PrivateEntryIterator.nextEntry (TreeMap.java:1208)
    at java.util.TreeMap$EntryIterator.next (TreeMap.java:1244)
    at java.util.TreeMap$EntryIterator.next (TreeMap.java:1239)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2554)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2578)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2546)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2578)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2546)
    at java.util.TreeMap.buildFromSorted (TreeMap.java:2503)
    at java.util.TreeMap.putAll (TreeMap.java:318)
    at org.codehaus.mojo.license.api.DependenciesTool.loadProjectDependencies (DependenciesTool.java:120)
    at org.codehaus.mojo.license.api.DefaultThirdPartyHelper.loadDependencies (DefaultThirdPartyHelper.java:152)
    at org.codehaus.mojo.license.AddThirdPartyMojo.loadDependencies (AddThirdPartyMojo.java:226)
    at org.codehaus.mojo.license.AbstractAddThirdPartyMojo.init (AbstractAddThirdPartyMojo.java:750)
    at org.codehaus.mojo.license.AbstractLicenseMojo.execute (AbstractLicenseMojo.java:171)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```

The issue is that `DefaultThirdPartyHelper#artifactCache` is shared between (and updated by) multiple threads without sufficient synchronization. I'll open a PR with a suggested fix.

### PR DESCRIPTION
**Pull request by Stephan202**

### CODE REVIEW

**Comment by bjanczak** [comment]
This fix resolves issue only partially. There is similar issue in DependenciesTool.java line 118.

**Comment by lama0206** [comment]
@bjanczak Why's there a problem in DependenciesTool? The localCache is imho tread-local and thus there's no concurrent access. The cache is read from the cache coming from the DefaultThirdPartyHelper which is thread-safe given this PR.

File: src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java [hunk 1]
```diff
@@ -138,7 +139,7 @@ public DefaultThirdPartyHelper( MavenProject project, String encoding, boolean v
     {
         if ( artifactCache == null )
         {
-            artifactCache = new TreeMap<>();
+            artifactCache = Collections.synchronizedSortedMap( new TreeMap<String, MavenProject>() );
```
Comment (lama0206) [inline src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:142]: I'd add double-checked locking:

wrap 142 like this:
synchronized(this); if(artifactCache==null) {
 --> initalization here
}

Comment (Stephan202) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:142]: @lama0206 interesting idea. Turns out `artifactCache` is static (yeah...), so synchronizing on `this` may not be enough. Could do this:
```suggestion
            synchronized (DefaultThirdPartyHelper.class)
            {
                if ( artifactCache == null )
                {
                    artifactCache = Collections.synchronizedSortedMap(new TreeMap<String, MavenProject>());
                }
            }
```

WDYT?

(It's been a long while since I looked at this code, so not sure whether this field _should_ be static. Can try to re-familiarize myself with the code later; likely not this evening.)

Comment (lama0206) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:142]: Yep,  @Stephan202,  that should be it. Thanks for double-checking :)

Concerning _static_: #398 discusses the artifactCache being static (and never released/cleaned) and thus eating memory for the entire mvn build. I think this issue (#354) is about correctness and #398 is about memory consumption. So I'd say that this here is fine.

Comment (Stephan202) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java]: Alright, rebased and updated the commit (squashed to keep history clean, since it appears in this repo squash-and-rebase isn't used much/at all).

Locally the `ISSUE-324/pom.xml` integration test fails, but that also happens on `master`. I was gonna say "let's see what happens on Travis CI", but it seems this repository hasn't been migrated to travis-ci.com yet, while travis-ci.org has ceased operations. Luckily there's also an AppVeyor build.)

**Comment by Stephan202** [comment]
Rebased. Would still be nice to get this PR merged :)

**Comment by frant-hartm** [comment]
Hi,

we are occasionally facing the #354 issue with the plugin when running a parallel build.

I have looked into @Stephan202's fix and I think additional modifications are needed:

- the field `artifactCache` must be volatile to prevent partially constructed object being used

- static private mutex object should be used instead of `SynchronizedMap.class`, one never knows who else might be synchronizing on that class

- All uses of `artifactCache` instance where it is being iterated over the elements must be manually synchronized, e.g. if you look at the following line 

https://github.com/mojohaus/license-maven-plugin/blob/5fb1c237dc22616116a7ae247ba87b38badb6983/src/main/java/org/codehaus/mojo/license/api/DependenciesTool.java#L120

it must be in a synchronized block on `cache` instance to prevent the concurrent modification failure. See the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedSortedMap-java.util.SortedMap-) of  `synchronizedSortedMap`

I believe these changes make the `AddThirdPartyMojo` thread-safe, so it can be marked as such.

I have made these changes available here https://github.com/frant-hartm/license-maven-plugin/commits/bugfix/issue-354

@Stephan202 you can either add them to this PR or I can send a separate PR with everything.

**Comment by Stephan202** [comment]
@frant-hartm thanks for breathing some life into this PR! You're totally right that the `synchronized (SortedMap.class)` construct was dodgy; thanks for calling that out :)

I cherry-picked your changes to the PR of this branch so that we can collaborate on them here. That said, I can totally understand if you eventually want to open a separate PR with these changes.

File: src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java [hunk 2]
```diff
@@ -185,9 +195,12 @@ public LicenseMap createLicenseMap( SortedMap<String, MavenProject> dependencies
 
         LicenseMap licenseMap = new LicenseMap();
 
-        for ( MavenProject project : dependencies.values() )
+        synchronized ( dependencies )
```
Comment (Stephan202) [inline src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:198]: (IIUC) this `dependencies` map is also used in a number of other places, and I don't see the code littered with `synchronized` blocks. Is this location special, or am I missing something?

NB: I'm not suggesting to "synchronize all the things": if that turns out to be necessary, perhaps we should look into a larger redesign. (But given the inactivity on this project, that seems risky, too.)

**Review by Stephan202 — COMMENTED** [review]
@frant-hartm I sent you an invite to be an outside collaborator on the Picnic fork; that might simplify collaboration :)

File: src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java [hunk 3]
```diff
@@ -458,13 +458,16 @@ public SortedProperties loadUnsafeMapping( LicenseMap licenseMap,
     {
         Map<String, MavenProject> snapshots = new HashMap<>();
 
-        //find snapshot dependencies
-        for ( Map.Entry<String, MavenProject> entry : artifactCache.entrySet() )
+        synchronized ( artifactCache )
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java:461]: This synchronized block prevents the `ConcurrentModificationException` - we can't iterate over its `entrySet` and modify it from other threads at the same time. Other operations like put/remove below are ok to use because we use the `synchronizedSortedMap`.

File: src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java (hunk 2 above)
Comment (frant-hartm) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:198]: This comes from here 

https://github.com/mojohaus/license-maven-plugin/blob/e29c4bf5c2d31adfd48dbaf0f18f27cee1960285/src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java#L750-L752

in the `AggregatorAddThirdPartyMojo` the `dependencies` is the `artifactCache`, so the iteration must be synchronized.

Comment (frant-hartm) [reply src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java:198]: Actually you are right, I have missed one usage here

https://github.com/mojohaus/license-maven-plugin/blob/4b868feaff88186d29179b9077ecca0575ee89a4/src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyHelper.java#L250

File: src/main/java/org/codehaus/mojo/license/api/DependenciesTool.java [hunk 4]
```diff
@@ -117,7 +117,10 @@ public SortedMap<String, MavenProject> loadProjectDependencies( ResolvedProjectD
         SortedMap<String, MavenProject> localCache = new TreeMap<>();
         if ( cache != null )
```
Comment (Stephan202) [inline src/main/java/org/codehaus/mojo/license/api/DependenciesTool.java:118]: NB: Here and further down the `null` check seems redundant, since IIUC callers never pass in `null`. (But we might not want to change this, in order to keep the PR minimal.)

**Review by Stephan202 — COMMENTED** [review]
Alright, I had my first coffee and refreshed my memory about this PR by reading the [`Collections.synchronizedSortedMap(java.util.SortedMap)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Collections.html#synchronizedSortedMap(java.util.SortedMap)) documentation. I traced the how the artifact cache is passed around, and I think all iteration operations are now synchronized. :muscle:

(This setup is still very fragile, since future modification can easily forget to add additional synchronization if necessary, but fixing that requires (much) larger changes.)

**Comment by Stephan202** [comment]
I was reminded of this PR because the issue it attempts to fix happened again.

@bjanczak @lama0206 @frant-hartm WDYT of the current state of the PR, and/or do you happen to know how we could get this merged and released?

**Comment by frant-hartm** [comment]
There are multiple issues with the current master - `mvnw` script is broken, failing tests, ...

Those probably need to be fixed first before merging any bugfixes.

Maybe someone who committed to master during the last year could help? @slawekjaranowski or @VonUniGE @slachiewicz @tpage-alfresco

**Comment by frant-hartm** [comment]
@olamy I see that you have released `2.0.1` recently, thanks a lot for your work.
Is there any way I can help to get this merged and released?

I would like to finally get rid of the following:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but this         *
[WARNING] * project contains the following plugin(s) that have goals not  *
[WARNING] * marked as thread-safe to support parallel execution.          *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against Apache Maven.                           *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked as thread-safe in Hazelcast Root:
[WARNING]   org.codehaus.mojo:license-maven-plugin:2.0.0
[WARNING] 
[WARNING] Enable debug to see precisely which goals are not marked as thread-safe.
[WARNING] *****************************************************************
```
and a flaky concurrent modification exception in our build :-)
